---
- name: Converge
  hosts: all

  vars:
    netbox_config:
      ALLOWED_HOSTS:
        - localhost
        - 127.0.0.1
      TIME_ZONE: Europe/Paris
    netbox_setup_ldap_auth: true
    netbox_setup_web_frontend: true
    netbox_ldap_config: "AUTH_LDAP_SERVER_URI = '127.0.0.1'"

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      register: package_result
      until: package_result is success
      when: ansible_os_family == 'Debian'

  roles:
    - role: gmazoyer.netbox
